dataset: ogbg-molpcba
aug: baseline
model_type: gnn-transformer
gnn_type: gin
gnn_virtual_node: true
graph_pooling: last
runs: 5
seed: 12344
batch_size: 256
lr: 0.0001
start-eval: 1
scheduler: plateau

transformer_norm_input: true
num_encoder_layers: 0
num_encoder_layers_masked: 4
transformer_prenorm: false
