dataset: ogbg-molhiv
aug: baseline
model_type: gnn-transformer
gnn_type: gin
gnn_virtual_node: true
graph_pooling: cls
runs: 5
seed: 12344
batch_size: 256
start-eval: 1
scheduler: cosine
lr: 0.0001

transformer_norm_input: true
