dataset: ogbg-molhiv
aug: baseline
model_type: gnn-transformer
gnn_type: gin
gnn_virtual_node: true
graph_pooling: cls
runs: 5
seed: 12344
batch_size: 256
start-eval: 1
scheduler: onecycle
lr: 0.0001
max_lr: 0.001
pct_start: 0.05
batch_size: 256
epochs: 60

transformer_norm_input: true
