dataset: ogbg-ppa
aug: baseline
model_type: gnn-transformer
gnn_type: gin
gnn_virtual_node: false
graph_pooling: mean
runs: 5
seed: 12344
batch_size: 256
lr: 0.0001
# grad_clip: 1
start-eval: 1
scheduler: plateau

transformer_norm_input: true
gnn_dropout: 0.5
epochs: 100