dataset: ogbg-molhiv
aug: baseline
model_type: multibranch
gnn_type: gin
gnn_virtual_node: true
graph_pooling: mean

runs: 5
seed: 12344
batch_size: 256
lr: 0.0001
start-eval: 1
scheduler: plateau

num_encoder_layers: 5
gnn_num_layer: 5